### PR TITLE
authenticatin and authorization started

### LINKED ISSUE #4: citizen login authorization and authentication
Citizen must be authorized to view the contents of the profile page

### PR DESCRIPTION
**Pull request by udofia2**
authentication and authorization about to be implemented

### CODE REVIEW

**Review by sleekLancelot — DISMISSED** [review]

**Review by udofia2 — COMMENTED** [review]
authorization done

**Review by sleekLancelot — DISMISSED** [review]
added more end points,nice

**Review by Timmymichael — DISMISSED** [review]
Nice implementation of the Authentication and authorization.

**Comment by sleekLancelot** [comment]
Ben you can reduce the review request to just 2 persons since no other person to review.

**Pull request merged**
